schedules:
- cron: '0 18 * * *'
  displayName: Daily 6pm build
  branches:
    include:
    - main

parameters:
- name: deployResources
  type: boolean
  default: false
  values:
  - true
  - false

pool:
  vmImage: windows-latest

stages:
  - stage: Deploy_Azure_Policy
    jobs:
    - job: Deploy_Azure_Policy
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: Deploy to Management Group Policy
        inputs:
          azureSubscription: 'azure-mvp-subscription'
          scriptLocation: 'inlineScript'
          scriptType: 'ps'
          inlineScript: |
            az stack group create `
              --resource-group 'dckloud-network-rg' `
              --name 'stack' `
              --template-file './bastion.bicep' `
              --parameters 'deployResources=$(deployResources)' `
              --deny-settings-mode 'none' `
              --action-on-unmanage deleteAll
