schedules:
- cron: '0 18 * * *'
  displayName: Daily 6pm build
  branches:
    include:
    - main

parameters:
- name: deployResources
  type: boolean
  default: false
  values:
  - true
  - false

pool:
  vmImage: windows-latest

stages:
  - stage: Deploy_Azure_Policy
    jobs:
    - job: Deploy_Azure_Policy
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: Deploy to Resources
        inputs:
          azureSubscription: 'azure-mvp-subscription'
          scriptLocation: 'inlineScript'
          scriptType: 'ps'
          inlineScript: |
            az account set --subscription 'Microsoft Azure Sponsorship'        
            az stack sub create `
              --name 'stack' `
              --template-file './main.bicep' `
              --location 'australiaeast' `s
              --parameters main.bicepparam deployResources=${{ parameters.deployResources }} `
              --action-on-unmanage deleteAll `
              --yes `
              --deny-settings-mode 'none'