schedules:
- cron: '0 6 * * *'
  displayName: Daily 6am build
  branches:
    include:
    - main
  always: true
  

parameters:
- name: deployResources
  type: boolean
  default: true
  values:
  - true
  - false

pool:
  vmImage: windows-latest

stages:
  - stage: Deploy_Azure_Stack
    jobs:
    - job: Deploy_Azure_Stack
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: Deploy to Reources
        inputs:
          azureSubscription: 'azure-mvp-subscription'
          scriptLocation: 'inlineScript'
          scriptType: 'ps'
          inlineScript: |
            az account set --subscription 'Microsoft Azure Sponsorship'        
            az stack sub create `
              --name 'stack' `
              --template-file '.\main.bicep' `
              --location 'australiaeast' `
              --parameters '.\main.bicepparam' `
              --parameters deployResources=${{ parameters.deployResources }} `
              --action-on-unmanage deleteAll `
              --yes `
              --deny-settings-mode 'none'